### ISSUE TITLE
mvn package - Failed to determine a suitable driver class

### ISSUE THREAD

**Issue by gregorwolf** [ionescuv/sap-cp-cf-starter#3]
As the Dokerfile for the app wants to COPY target/demo-0.0.1-SNAPSHOT.jar app.jar into the container I had to build the jar first. I've issued

``` 
 mvn clean package
``` 

but the build fails with: 

``` 
Reason: Failed to determine a suitable driver class
``` 

When I rename the file DemoApplicationTests.java to DemoApplicationTests.xjava I get a build without tests.

**Comment by ionescuv** [comment]
Looks like the database connection is not configured properly for the integration test. I'll adjust the test

**Comment by matzeeable** [comment]
I have the same issue. I think this has something to do with [`application.properties`](https://github.com/ionescuv/sap-cp-cf-starter/blob/master/src/app/src/main/resources/application.properties) file because it is empty. Relates to https://github.com/spring-projects/spring-boot/issues/13796 I think. How I have to configure that file to make it work locally and with CF? :-)

**Comment by ionescuv** [comment]
The application should always be started using the CLOUD profile, both locally and in CloudFoundry (the scripts should already be doing that for you). In the CLOUD profile, the DB configuration is read from the application environment.

The problem arises in the integration test, since it wasn't configured to run in the CLOUD profile.
To overcome the problem, assuming you have a postgresql DB running on localhost:5432, you can put something like this in the application properties file: 
```
spring.datasource.url = jdbc:postgresql://localhost:5432/postgres
spring.datasource.username = YOUR_USER_HERE
spring.datasource.password = YOUR_PWD_HERE
spring.datasource.platform = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name = org.postgresql.Driver
```
